name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      bin_name: zotit
    steps:
    - uses: actions/checkout@v3

    - name: Install prequisites
      run: |
        sudo apt install zip 

    - name: Build V2
      run: |
        mkdir -p distv2
        cp -r assets distv2/
        cp -r pages distv2/
        cp app.js distv2/ 
        cp app.css distv2/ 
        cp config.js distv2/ 
        cp index.html distv2/ 
        cp manifest2.json distv2/ 
        mv distv2/manifest2.json distv2/manifest.json
    
    - name: Zip distv2
      run: cd distv2 && zip -r distv2.zip .
    
    - name: Build V3
      run: |
        mkdir -p distv3
        cp -r assets distv3/
        cp -r pages distv3/
        cp app.js distv3/ 
        cp app.css distv3/ 
        cp config.js distv3/ 
        cp index.html distv3/ 
        cp manifest3.json distv3/ 
        mv distv3/manifest3.json distv3/manifest.json

    - name: Zip distv3
      run: cd distv3 && zip -r distv3.zip .
    

    - name: release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: ${{ github.token }}
        automatic_release_tag: ${{ github.ref }}
        prerelease: false
        title: ${{ github.event.head_commit.message }}
        files: |
          ./distv2/distv2.zip
          ./distv3/distv3.zip